apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  example.property: "example value"
  example.property2: "another example value"

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # Base64 encoded "password"
  secret: c2VjcmV0  # Base64 encoded "secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret1
type: Opaque
data:
  password: cGFzc3dvcmQx  # Base64 encoded "password1"
  secret: c2VjcmV0MQ==  # Base64 encoded "secret1"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret2
type: Opaque
data:
  myconfig__password2: cGFzc3dvcmQy  # Base64 encoded "password2"
  myconfig__secret2: c2VjcmV0Mg==  # Base64 encoded "secret2"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret3
type: Opaque
data:
  myconfig__password3: cGFzc3dvcmQz  # Base64 encoded "password3"
  myconfig__secret3: c2VjcmV0Mw==  # Base64 encoded "secret3"