{
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
        "name": "test-minimal",
        "creationTimestamp": null,
        "labels": {
            "app": "test-minimal"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "app": "test-minimal"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "app": "test-minimal"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "minimal",
                        "image": "minimal:latest",
                        "imagePullPolicy": "Never",
                        "resources": {}
                    }
                ]
            }
        },
        "strategy": {}
    },
    "status": {}
}