apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader-service-account
  namespace: default
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
secrets:
  - name: example-secret
  - name: example-secret1
  - name: example-secret2
  - name: example-secret3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-no-reader-service-account
  namespace: default
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - "example-secret"
    - "example-secret1"
    - "example-secret2"
    - "example-secret3"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-reader-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames:
    - "example-config"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secret-reader-service-account
  namespace: default
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-deny-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - "example-secret"
    - "example-secret1"
    - "example-secret2"
    - "example-secret3"
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-deny-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secret-no-reader-service-account
  namespace: default
roleRef:
  kind: Role
  name: secret-deny-role
  apiGroup: rbac.authorization.k8s.io
---
