apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: minimal1
  name: minimal1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minimal1
    spec:
      containers:
      - image: minimal:latest
        name: minimal1
        resources: {}
        imagePullPolicy: Never
        ports:
        - containerPort: 5095
        env:
        - name: MR_minimal1
          value: "11111111111111"
        livenessProbe: # Add this section to add a liveness probe
          httpGet:
            path: /info
            port: 5095
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minimal1
  name: minimal1
spec:
  ports:
  - name: minimal1
    port: 80
    protocol: TCP
    targetPort: 5095
  selector:
    app: minimal1
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: minimal1-ingress
  annotations:
    11111111111: 'added in the manifest'
spec:
  rules:
  - host: my-k8s-example1.com
    http:
      paths:
      - backend:
          service:
            name: minimal1
            port:
              number: 5095
        path: /
        pathType: Prefix