apiVersion: v1
kind: Namespace
metadata:
  name: service-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwsh-deployment
  namespace: service-test
  labels:
    app: pwsh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwsh
  template:
    metadata:
      labels:
        app: pwsh
    spec:
      containers:
      - name: pwsh
        image: mcr.microsoft.com/powershell
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          requests:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "500Mi"
        # set history path to root to avoid permission issues when it tries to save history
        command: ['pwsh','-Command','Set-PSReadLineOption -HistorySavePath /; $PSVersionTable | Out-String;while ($true) { Start-Sleep -Seconds 10 }']